#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}python setup.py build sdist bdist_wheel
${PREFIX}twine check dist/*
rm -r build

${PREFIX}mkdocs build
