#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}black --check --diff --target-version=py36 tartiflette_asgi tests setup.py
${PREFIX}mypy tartiflette_asgi
${PREFIX}flake8 tartiflette_asgi tests setup.py
