#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi

if [ -d 'build' ] ; then
    rm -r build
fi

if [ -d 'site' ] ; then
    rm -r site
fi

if [ -d 'htmlcov' ] ; then
    rm -r htmlcov
fi

if [ -d 'tartiflette_starlette.egg-info' ] ; then
    rm -r tartiflette_starlette.egg-info
fi
