#!/bin/sh -e

export SOURCE_FILES="src tests setup.py"
export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}autoflake --in-place --recursive $SOURCE_FILES
${PREFIX}seed-isort-config --application-directories=tartiflette_asgi
${PREFIX}isort $SOURCE_FILES
${PREFIX}black --target-version=py36 $SOURCE_FILES

scripts/check
