#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

find src -type f -name "*.py[co]" -delete
find src -type d -name __pycache__ -delete

${PREFIX}twine upload dist/*
${PREFIX}mkdocs gh-deploy
