#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

PACKAGE="tartiflette_asgi"
VERSION=`python -c "import $PACKAGE; print($PACKAGE.__version__)"`

find ${PACKAGE} -type f -name "*.py[co]" -delete
find ${PACKAGE} -type d -name __pycache__ -delete

${PREFIX}twine upload dist/*
${PREFIX}mkdocs gh-deploy
